In [1]:
import numpy as np

# Определим функции активации и их производные
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Подготовка данных
inputs = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]])

outputs = np.array([[0], [1], [1], [0]])

# Инициализация весов случайными числами
np.random.seed(42)
input_layer_neurons = inputs.shape[1]
hidden_layer_neurons = 2
output_neurons = 1

# Веса между входным и скрытым слоем
hidden_weights = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
hidden_bias = np.random.uniform(size=(1, hidden_layer_neurons))

# Веса между скрытым и выходным слоем
output_weights = np.random.uniform(size=(hidden_layer_neurons, output_neurons))
output_bias = np.random.uniform(size=(1, output_neurons))

# Определение количества итераций и скорости обучения
epochs = 10000
learning_rate = 0.1

# Обучение модели
for epoch in range(epochs):
    # Прямое распространение
    hidden_layer_input = np.dot(inputs, hidden_weights) + hidden_bias
    hidden_layer_activation = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_activation, output_weights) + output_bias
    predicted_output = sigmoid(output_layer_input)

    # Вычисление ошибки
    error = outputs - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    # Обратное распространение
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_activation)

    # Обновление весов и смещений
    output_weights += hidden_layer_activation.T.dot(d_predicted_output) * learning_rate
    output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    hidden_weights += inputs.T.dot(d_hidden_layer) * learning_rate
    hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

    if (epoch + 1) % 1000 == 0:
        print(f'Epoch {epoch+1}, Error: {np.mean(np.abs(error))}')

# Проверка результата
print("Input:\n", inputs)
print("Actual Output:\n", outputs)
print("Predicted Output:\n", predicted_output)


Epoch 1000, Error: 0.4896533821967359
Epoch 2000, Error: 0.4305879058698948
Epoch 3000, Error: 0.3358864269931021
Epoch 4000, Error: 0.17367683205658846
Epoch 5000, Error: 0.11184946532482275
Epoch 6000, Error: 0.08578266819752217
Epoch 7000, Error: 0.0713199793269066
Epoch 8000, Error: 0.06198291159412562
Epoch 9000, Error: 0.05537784300303635
Epoch 10000, Error: 0.0504138959056583
Input:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Actual Output:
 [[0]
 [1]
 [1]
 [0]]
Predicted Output:
 [[0.05322146]
 [0.95171535]
 [0.95160449]
 [0.05175396]]
